on:
    push:
        branches: [ "master", "fix-build" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
            python-version: 'pypy2.7' 
      
      - name: Prepare
        run: |
            sudo apt-get install autoconf automake bison flex gcc libelf-dev make \
            texinfo libncurses5-dev patch python3 subversion wget zlib1g-dev \
            libtool libtool-bin python3-dev bzip2 libgmp3-dev pkg-config g++ \
            libssl-dev clang xutils-dev nvidia-cg-toolkit

            export PS3DEV=/usr/local/ps3dev
            export PSL1GHT=$PS3DEV
            export PATH=$PATH:$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin

            sudo mkdir -p $PS3DEV
            sudo chown -R $USER: $PS3DEV
            wget https://github.com/ps3dev/ps3dev/releases/download/nightly-2026-07-26/ps3dev-linux-X64.tar.gz
            tar --strip-components=1 -xzvf ps3dev-linux-X64.tar.gz -C $PS3DEV
            rm ps3dev-linux-X64.tar.gz

            wget https://download.gnome.org/sources/libxml2/2.9/libxml2-2.9.14.tar.xz
            tar xvf libxml2-2.9.14.tar.xz
            cd libxml2-2.9.14
            ./configure --with-python=/opt/hostedtoolcache/PyPy/2.7.18/x64/bin/python --prefix=/usr
            make -j$(nproc)
            sudo make install
            echo && echo
            ls /opt/hostedtoolcache/PyPy/2.7.18/x64/
            

      - name: Build
        run: |
            export PS3DEV=/usr/local/ps3dev
            export PSL1GHT=$PS3DEV
            export PATH=$PATH:$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin
            export PYTHON=/opt/hostedtoolcache/PyPy/2.7.18/x64/bin/python
            
            autoreconf -fiv
            mkdir $HOME/OUT
            ./configure --with-ppu-prefix=$HOME/OUT --prefix=$HOME/OUT --disable-samples
            make -j$(nproc)
            make install
            find $HOME/OUT
            7z a OUT.zip $HOME/OUT

      - uses: actions/upload-artifact@v4
        with:
          path: OUT.zip
