on:
    push:
        branches: [ "master", "fix-build" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/miigotu/ps3toolchain/ps3dev:submodules
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: |
            apt install software-properties-common
            apt-add-repository contrib
            apt-add-repository non-free

            wget http://security.debian.org/debian-security/pool/updates/main/libx/libxml2/python-libxml2_2.9.4+dfsg1-7+deb10u6_amd64.deb
            printf "deb http://deb.debian.org/debian bullseye main\n" > /etc/apt/sources.list.d/bullseye.list
            printf "deb http://deb.debian.org/debian bullseye-updates main\n" >> /etc/apt/sources.list.d/bullseye.list
            printf "deb http://security.debian.org bullseye-security main" >> /etc/apt/sources.list.d/bullseye.list
            cat /etc/apt/sources.list.d/bullseye.list

            apt update
            apt-get install python2 ./python-libxml2_2.9.4+dfsg1-7+deb10u6_amd64.deb xutils-dev nvidia-cg-toolkit

            PYTHON=/usr/bin/python2 ./configure
            make -j$(nproc)
