on:
    push:
        branches: [ "master", "fix-build" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: scummvm/dockerized-toolchains:ps3
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: |
            printf "deb http://deb.debian.org/debian bullseye main\n"         >> /etc/apt/sources.list.d/bullseye.list
            printf "deb http://deb.debian.org/debian bullseye-updates main\n" >> /etc/apt/sources.list.d/bullseye.list
            printf "deb http://security.debian.org bullseye-security main"    >> /etc/apt/sources.list.d/bullseye.list
            cat /etc/apt/sources.list.d/bullseye.list

            apt update
            wget http://security.debian.org/debian-security/pool/updates/main/libx/libxml2/python-libxml2_2.9.4+dfsg1-7+deb10u6_amd64.deb
            apt-get install python2 ./python-libxml2_2.9.4+dfsg1-7+deb10u6_amd64.deb xutils-dev autotools-dev autoconf -y

            autoreconf -fiv
            PYTHON=/usr/bin/python2 ./configure --disable-samples
            make -j$(nproc)
